apiVersion: v2
name: cloudcasa
version: "3.6.0"
appVersion: "3.6.0"
kubeVersion: ">=1.20.0-0"
description: CloudCasa Test v3.6.0
home: https://cloudcasa.io
icon: https://raw.githubusercontent.com/catalogicsoftware/cloudcasa-helmchart/gh-pages/logo.png
keywords:
  - backup
  - restore
  - migration
  - catalogic
  - cloudcasa
  - velero
maintainers:
  - name: catalogicsoftware
    email: support@cloudcasa.io
